package main

// Topic clusters ported from the old backend/seed.py: a tag pool plus ja/en
// sentence pools per topic, so the Sense-Distance ranker has real semantic
// structure to work with. Mixed ja/en on purpose (one language per post).

type cluster struct {
	name string
	tags []string
	ja   []string
	en   []string
}

var clusters = []cluster{
	{
		name: "infra",
		tags: []string{"kubernetes", "k8s", "docker", "terraform", "aws", "gcp", "devops",
			"observability", "sre", "platform engineering"},
		ja: []string{
			"本番のKubernetesでオートスケールがやっと安定した。閾値をCPUからリクエスト同時数に変えたのが効いた。",
			"Terraformのstateをチームで共有し始めてから、深夜の手動オペがほぼ消えた。",
			"コスト最適化はインスタンスサイズより、まず使ってないボリュームとロードバランサを消すのが一番効く。",
			"監視はメトリクスよりまずログの構造化から。後から効いてくる投資だと痛感している。",
			"障害対応で学んだのは、ロールバックを1コマンドにしておくことが何より大事だということ。",
			"マネージドに寄せるほど運用は楽になるが、ベンダーロックインとのバランスは常に悩ましい。",
			"SREのエラーバジェットを真面目に運用したら、無駄なアラートが7割減った。",
			"コンテナのイメージサイズを削るだけでデプロイ時間が体感で半分になった。地味だが効く。",
			"インフラのコードレビューで一番見るのは権限の最小化。ここを雑にすると後で必ず痛い目を見る。",
			"可観測性は『なぜ遅いか』を5分で説明できる状態を指す。ダッシュボードの数ではない。",
			"オンコールを持つようになって、設計時に『3時に叩き起こされても直せるか』を考えるようになった。",
			"クラウド請求書を毎週見る習慣をつけたら、アーキテクチャの意思決定が現実的になった。",
		},
		en: []string{
			"Spent the day taming a Kubernetes rollout; switching the HPA from CPU to in-flight requests finally made it stable.",
			"Moving Terraform state into a shared backend killed almost all of our late-night manual ops.",
			"The cheapest cost win is rarely instance sizing — it's deleting the orphaned volumes and idle load balancers nobody owns.",
			"Observability isn't the number of dashboards; it's being able to explain why something is slow in five minutes.",
			"The biggest lesson from our last incident: make the rollback a single command before you ship anything.",
			"Trimming the container image cut our deploy time roughly in half. Unglamorous, but it compounds.",
			"Every infra review I do now starts with least-privilege — get that wrong and it hurts later, guaranteed.",
			"Going on-call changed how I design: I now ask whether I could fix this at 3am, half asleep.",
			"Managed services make ops easier but the lock-in trade-off never really goes away.",
			"We started reading the cloud bill every Friday and suddenly architecture decisions got a lot more grounded.",
			"Structured logging first, fancy metrics later — that ordering has paid off every single time.",
			"An error budget you actually enforce will delete more pager noise than any alerting tool.",
		},
	},
	{
		name: "data_ml",
		tags: []string{"machine learning", "vector search", "embeddings", "snowflake",
			"data engineering", "nlp", "llm", "recommendation", "rag", "etl"},
		ja: []string{
			"推薦に類似度だけを使うとエコーチェンバーになる。あえて『遠いけど価値観が重なる』投稿を混ぜると体験が変わる。",
			"ベクトル検索はインデックスの再構築を前提に設計すると一気に運用が楽になる。真実は別のDBに置く。",
			"埋め込みのモデルを変えるより、前処理を丁寧にする方が精度が上がることが多い。",
			"RAGは検索が9割。生成モデルを大きくする前に、まず検索の評価指標を整えるべきだった。",
			"レイテンシを半分にできた一番の要因は、候補生成と再ランクを分離したこと。",
			"データ基盤の負債は『誰も意味を説明できないカラム』として静かに溜まっていく。",
			"オフライン評価とオンラインの数字がずれる時、だいたい原因はログの取り方にある。",
			"次元削減はかっこいいが、まずは素朴な共起の集計が一番説明しやすくて強い。",
			"推薦の多様性をKPIに入れたら、短期のクリックは少し下がったが継続率が上がった。",
			"ETLは冪等にしておくと、障害から戻すのが怖くなくなる。これは精神衛生の投資。",
			"埋め込みの可視化をチームに見せると、モデルが何を『近い』と思っているかの議論が一気に進む。",
			"LLMに頼る前に、ルールベースで8割解ける問題なのかを必ず見積もるようにしている。",
		},
		en: []string{
			"Ranking on pure similarity quietly builds an echo chamber; mixing in 'far but shares a value' posts changes the whole feel.",
			"Design your vector index assuming you'll rebuild it; keep the source of truth somewhere else and operations get much calmer.",
			"More often than not, better preprocessing beats swapping the embedding model for accuracy.",
			"RAG is 90% retrieval. I should have fixed the retrieval metrics before reaching for a bigger generator.",
			"The single biggest latency win came from splitting candidate generation from reranking.",
			"Data debt accumulates silently as columns no one can explain the meaning of anymore.",
			"When offline eval and online numbers disagree, the culprit is usually how you logged things.",
			"Dimensionality reduction looks cool, but a plain co-occurrence count is often stronger and far easier to explain.",
			"We put recommendation diversity into the KPIs; short-term clicks dipped a little, retention went up.",
			"Make your ETL idempotent and recovering from failure stops being scary — it's an investment in sanity.",
			"Showing the team an embedding projection moves the 'what does the model think is similar' debate forward fast.",
			"Before reaching for an LLM I always estimate whether rules already solve 80% of the problem.",
		},
	},
	{
		name: "frontend",
		tags: []string{"react", "typescript", "vite", "tailwind", "ux", "design systems",
			"accessibility", "frontend", "web performance", "animation"},
		ja: []string{
			"良いコンポーネントは追加ではなく削除で完成することが多い。状態を一つ消すたびにバグも消える。",
			"アクセシビリティは最後の味付けではなく最初の制約として入れると、結局UIが綺麗になる。",
			"楽観的更新を入れたら『いいね』の体感が別物になった。サーバー応答を待つUIは想像以上に遅く感じる。",
			"デザインシステムは見た目の統一より『意思決定の数を減らす』ことに価値がある。",
			"Viteに移ってからビルド待ちのストレスが消えて、試行回数が増えた。これが一番の効果。",
			"TypeScriptの型は仕様書として読める。コメントより型を厚くする方が後で助かる。",
			"アニメーションは『気づかれないくらい』が上手い。派手さは初回だけ嬉しい。",
			"モバイル幅で先に作ると、情報の優先順位を強制的に考えることになって設計が締まる。",
			"パフォーマンスはバンドルサイズより、まず再レンダリングの回数を疑うのが早い。",
			"フォームのバリデーションはエラーの出し方が9割。文言ひとつで離脱率が変わる。",
			"ダークテーマは『黒に近い灰』とコントラストの設計が肝で、純黒は逆に読みにくい。",
			"UIの良し悪しは、迷わず次の操作に進めるかで決まる。装飾はその後の話。",
		},
		en: []string{
			"A good component is usually finished by deleting, not adding; every state you remove takes a bug with it.",
			"Treat accessibility as an upfront constraint, not a final garnish, and the UI ends up cleaner anyway.",
			"Optimistic updates made 'like' feel like a different product; waiting on the server is slower than you think.",
			"A design system's real value is reducing the number of decisions, not unifying the pixels.",
			"Since moving to Vite the build-wait stress is gone, so I just try more things — that's the actual win.",
			"Types read like a spec. Investing in stronger types pays off more than another comment.",
			"The best animation is the one you barely notice; flashy only delights on the first view.",
			"Designing mobile-first forces you to rank information, and that discipline tightens the whole layout.",
			"For performance, suspect re-render counts before bundle size — it's usually the faster path.",
			"Form validation is 90% about how you surface the error; one line of copy moves the drop-off rate.",
			"Dark themes live or die on near-black greys and contrast; pure black is actually harder to read.",
			"UI quality comes down to whether people reach the next action without hesitating; decoration comes after.",
		},
	},
	{
		name: "ethics_comm",
		tags: []string{"ethics", "communication", "philosophy", "society", "empathy",
			"debate", "opinion", "community", "psychology", "values"},
		ja: []string{
			"意見が違うこと自体は問題じゃない。共有する価値観が見えなくなった時に対立が壊れる。",
			"あえて自分と反対の立場の記事を読む習慣を続けている。腹は立つが、世界の解像度は上がる。",
			"議論で勝つことより、相手の前提を正確に言い換えられるかを大事にしたい。",
			"共感は同意ではない。同意できなくても理解しようとする姿勢が会話を生かす。",
			"SNSの設計は人の振る舞いを作る。仕組みが煽れば、優しい人でも刺々しくなる。",
			"遠い立場の人と一度ちゃんと話すと、相手も同じくらい怖がっていたと気づくことが多い。",
			"正しさを主張する前に、自分が間違っているかもしれない確率を口に出すと議論が柔らかくなる。",
			"コミュニティが健全かは、少数意見が安全に出せるかで測れると思う。",
			"倫理は答えの集合ではなく、迷い続けるための問いの作法に近い。",
			"言葉を選ぶことは弱さではない。むしろ相手を一人の人間として扱う最低限の礼儀だ。",
			"分断はアルゴリズムだけのせいではない。私たちが快適さを選び続けた結果でもある。",
			"対話の目的は説得ではなく、共有できる土台を一つ見つけること。それで十分前進だ。",
		},
		en: []string{
			"Disagreement itself isn't the problem; things break when the shared values stop being visible.",
			"I keep reading pieces I strongly disagree with. It's irritating, but my picture of the world gets sharper.",
			"I care less about winning an argument than about restating the other side's premise accurately.",
			"Empathy isn't agreement; trying to understand even when you can't agree is what keeps a conversation alive.",
			"Platform design shapes behavior — if the mechanics reward outrage, even kind people get sharp.",
			"Talk honestly with someone far from your view and you often find they were just as scared as you.",
			"Saying out loud that you might be wrong, before asserting you're right, softens almost any debate.",
			"You can measure a community's health by how safely a minority opinion can be voiced.",
			"Ethics is less a set of answers than a discipline for staying uncertain well.",
			"Choosing your words carefully isn't weakness; it's the minimum courtesy of treating someone as a person.",
			"Polarization isn't only the algorithm's fault — it's also the comfort we kept choosing.",
			"The goal of dialogue isn't persuasion but finding one shared piece of ground; that alone is progress.",
		},
	},
	{
		name: "lifestyle",
		tags: []string{"coffee", "travel", "running", "cooking", "books", "photography",
			"minimalism", "music", "gardening", "tea"},
		ja: []string{
			"朝のコーヒーを丁寧に淹れる10分が、一日の集中の質を決めている気がする。",
			"久しぶりに走り始めたら、考えごとが勝手に整理されていくのに驚いた。距離より頻度。",
			"物を減らすほど、本当に好きなものが何かがはっきりしてくる。ミニマリズムは引き算の発見だ。",
			"料理は失敗しても食べられる、というのが良い。コードと違って即フィードバックが返ってくる。",
			"旅は予定を詰めすぎないほうが記憶に残る。余白の時間に一番いい出会いがある。",
			"写真を撮るようになって、見慣れた通勤路にも光の良い瞬間があると気づけるようになった。",
			"積読が増えてきたので、月に一冊は最後まで読むと決めた。読了の満足は何にも代えがたい。",
			"お茶を淹れる所作には、急いでいる自分を一度止めるスイッチのような効果がある。",
			"ベランダで野菜を育て始めたら、天気予報を見る目が変わった。生活が少し地に足がついた。",
			"音楽は作業用と鑑賞用を分けると、どちらの時間も濃くなる。ながら聴きは贅沢を薄める。",
			"週末に何もしない時間を意図的に確保したら、平日の判断が速くなった。休息は生産性の一部だ。",
			"小さな習慣ほど効果は複利で効く。派手な決意より、続く仕組みを作るほうが勝つ。",
		},
		en: []string{
			"The ten careful minutes I spend on morning coffee seem to set the quality of the whole day's focus.",
			"Started running again and was surprised how it sorts my thoughts on its own — frequency beats distance.",
			"The less I own, the clearer it gets what I actually love; minimalism is discovery by subtraction.",
			"Cooking is forgiving — unlike code, the feedback is immediate and you can still eat the mistake.",
			"Trips stick in memory when you don't overschedule them; the best encounters happen in the empty hours.",
			"Since I started taking photos I notice that even my dull commute has moments of good light.",
			"My unread stack got tall, so I committed to finishing one book a month; nothing beats that satisfaction.",
			"Brewing tea works like a switch that stops the rushing version of me for a moment.",
			"Growing a few vegetables on the balcony changed how I read the weather forecast — life feels grounded.",
			"Splitting music into 'for work' and 'for listening' made both kinds of time richer.",
			"Deliberately protecting a do-nothing block on weekends made my weekday decisions faster; rest is part of output.",
			"Small habits compound; a system that lasts beats a dramatic resolution every time.",
		},
	},
	{
		name: "startup",
		tags: []string{"startup", "product", "growth", "fundraising", "hiring",
			"go to market", "metrics", "founder", "pricing", "strategy"},
		ja: []string{
			"スタートアップで一番難しいのは、良いが脇道なアイデアに『ノー』と言うこと。",
			"指標を一つに絞ったらチームの動きが明らかに速くなった。北極星は本当に一つでいい。",
			"採用は急ぐと必ず後で時間を失う。最初の10人はカルチャーそのものになる。",
			"価格は機能ではなく価値で決める。安く出すと、安さでしか選ばれない顧客が集まる。",
			"失敗から学んだのは、作る前に売れるかを確かめる順番を間違えないこと。",
			"資金調達は手段であって目的じゃない。調達額を自慢し始めたら危ない兆候だ。",
			"プロダクトの良し悪しは、ユーザーが友達に説明できる一文があるかで決まる。",
			"成長は派手な施策より、解約の理由を一つずつ潰す地味な作業の積み重ねだった。",
			"創業者の仕事の半分は、全員が同じ絵を見ている状態を作り直し続けること。",
			"最初の顧客10人とは過剰なくらい話す。スケールしないことをやる時期は確かにある。",
			"戦略とは『やらないことを決める』こと。全部やろうとした四半期は全部中途半端だった。",
			"市場投入は完璧を待つより、恥ずかしいくらい早く出して反応で学ぶ方が結局速い。",
		},
		en: []string{
			"The hardest part of a startup is saying no to good-but-distracting ideas.",
			"Narrowing to a single metric visibly sped the team up; you really only need one north star.",
			"Rush hiring and you lose the time later — the first ten people literally become the culture.",
			"Price on value, not features; sell cheap and you attract customers who only chose you for cheap.",
			"The lesson from getting it wrong twice: don't invert the order — validate demand before you build.",
			"Fundraising is a means, not the goal; bragging about the round size is an early warning sign.",
			"A product is good when the user has one sentence to explain it to a friend.",
			"Growth turned out to be the unglamorous work of killing churn reasons one at a time.",
			"Half a founder's job is continually rebuilding the state where everyone sees the same picture.",
			"Talk to your first ten customers excessively; there is a real season for doing things that don't scale.",
			"Strategy is deciding what not to do; the quarter I tried to do everything, everything came out half-done.",
			"Shipping embarrassingly early and learning from reactions beats waiting for perfect, almost every time.",
		},
	},
	{
		name: "ramen",
		tags: []string{"ラーメン", "二郎系", "家系", "豚骨", "醤油ラーメン", "味噌ラーメン",
			"つけ麺", "替え玉", "背脂", "コール"},
		ja: []string{
			"二郎系のコールはニンニクマシマシにしがちだけど、翌日のことを考えると普通で止める勇気も大事。",
			"家系は麺の硬さ・味の濃さ・油の量を全部『普通』で頼んで、まず店の基準を知るのが一番うまい食べ方だと思う。",
			"豚骨の替え玉はバリカタで頼んで、最後にスープを吸って柔らかくなったところを楽しむ派。",
			"つけ麺は割りスープがあるかで満足度が変わる。最後まで飲み干せる設計は店の優しさだと思う。",
			"二郎はロットを乱さないのがマナー。食べ切れる量をコールするまでが二郎だと教わった。",
			"家系のライスは、海苔でスープを吸わせてご飯に乗せる瞬間が一番の贅沢。",
			"札幌で食べた味噌ラーメンは別物だった。背脂と生姜の効かせ方がそもそも違う。",
			"塩ラーメンこそ店の実力が出る。誤魔化しが効かない正直なスープが好き。",
			"ヤサイマシは最初にカエシと絡めてから食べると、味がぼやけずに最後まで持つ。",
			"替え玉は博多の発明だと思う。一玉目は少なめ、二玉目で好みを攻めるのが楽しい。",
			"背脂は悪者にされがちだけど、適量はコクと甘みの源。要は塩分とのバランス。",
			"行列の時間も込みで一杯だと思っている。並んでいるあいだに期待が育つ。",
		},
		en: []string{
			"Jiro-style ramen is a ritual: the call — garlic, veg, fat, sauce — is half the experience.",
			"With iekei, order everything 'normal' first to learn the shop's baseline, then tune from there.",
			"Tonkotsu kaedama is best ordered firm, then softened in the last of the broth.",
			"A good tsukemen shop hands you broth to dilute at the end; finishing the bowl is a kindness.",
			"Back-fat gets a bad rap, but in the right amount it's where the richness and sweetness come from.",
		},
	},
	{
		name: "vtuber",
		tags: []string{"vtuber", "切り抜き", "スパチャ", "同接", "推し活",
			"配信", "歌ってみた", "デビュー配信", "卒業", "箱推し"},
		ja: []string{
			"推しの切り抜きから入って、気づいたら本配信を追ってる。これは界隈あるあるだと思う。",
			"赤スパを投げるか毎回悩むけど、好きな瞬間に感謝を残せるのは良い文化だと思っている。",
			"同接の数字だけで価値を測るのは違う。少人数の枠の濃さは数字には出ない。",
			"初見さんに優しい配信者は、コメントの拾い方が本当にうまい。",
			"新衣装お披露目や歌ってみたの投稿は、ファンにとってちょっとした祭りなんだよな。",
			"卒業配信は寂しいけど、最後まで前向きに送り出せるファンの空気が好き。",
			"箱推しになると、コラボのたびに関係性が深まっていくのが嬉しい。",
			"スパチャは投げ銭である前に、感謝を可視化する手段だと思っている。",
			"切り抜き師の編集センスで、同じ配信でも面白さが何倍にもなる。",
			"デビュー配信のあの初々しい緊張感は一度きり。何度見返しても良い。",
			"凸待ちや誕生日配信は、普段絡まない箱同士の関係が見られて楽しい。",
			"推し活は無理しない範囲で長く続けるのが一番。その方が結局しあわせ。",
		},
		en: []string{
			"You come for the clips and stay for the streams — that's the whole VTuber funnel.",
			"Concurrent-viewer counts don't capture how intense a small channel's chat can be.",
			"A red superchat is less a tip than a way to make gratitude visible in the moment.",
			"Clippers' editing turns the very same stream into something several times funnier.",
			"Debut and graduation streams hit hardest — fans growing up alongside a character is the whole appeal.",
		},
	},
}

var commentTexts = []string{
	"なるほど、その視点はなかった。", "完全に同意。", "ここ、もう少し詳しく聞きたい。",
	"I see it differently, but this is well put.", "Saved this — thanks for sharing.",
	"反対の立場だけど、考えさせられた。", "実体験に基づいていて説得力がある。",
	"This matches what we saw in production.", "後半の指摘が刺さった。", "自分も最近同じことを考えていた。",
}
