import { Loader2, Send, X, Sparkles } from "lucide-react"
import type React from "react"
import { useState, useEffect, useRef } from "react"
import { useMutation, useQueryClient } from "@tanstack/react-query"
import { createPost, suggestPOVs, generatePOVs } from "../api/client"
import type { User } from "../api/client"

interface PostInputFormProps {
  user: User | null
  onAuthRequired: () => void
  onPostCreated?: () => void
}

export const PostInputForm: React.FC<PostInputFormProps> = ({ user, onAuthRequired, onPostCreated }) => {
  const [inputText, setInputText] = useState<string>("")
  const [manualPOVInput, setManualPOVInput] = useState<string>("")
  const [manualPOVs, setManualPOVs] = useState<string[]>([])
  const [autoGeneratedPOVs, setAutoGeneratedPOVs] = useState<string[]>([])
  const [isGeneratingPOVs, setIsGeneratingPOVs] = useState(false)
  const [povSuggestions, setPOVSuggestions] = useState<string[]>([])
  const [showPOVSuggestions, setShowPOVSuggestions] = useState(false)
  const povInputRef = useRef<HTMLInputElement>(null)

  const queryClient = useQueryClient()

  // Auto-generate POVs from text content
  useEffect(() => {
    if (!inputText.trim()) {
      setAutoGeneratedPOVs([])
      setIsGeneratingPOVs(false)
      return
    }

    setIsGeneratingPOVs(true)
    const timer = setTimeout(async () => {
      try {
        const generatedPOVs = await generatePOVs(inputText)
        // Filter out POVs that are already manually added
        const filteredPOVs = generatedPOVs.filter(
          (pov) => !manualPOVs.includes(pov) && pov.length <= 300
        )
        setAutoGeneratedPOVs(filteredPOVs)
      } catch (error) {
        console.error("Failed to generate POVs from text", error)
        setAutoGeneratedPOVs([])
      } finally {
        setIsGeneratingPOVs(false)
      }
    }, 800) // Debounce for 800ms

    return () => {
      clearTimeout(timer)
      setIsGeneratingPOVs(false)
    }
  }, [inputText, manualPOVs])

  // POV suggestions for manual input
  useEffect(() => {
    // Always fetch suggestions when input changes (empty query returns popular POVs)
    const timer = setTimeout(async () => {
      try {
        const query = manualPOVInput.trim()
        const suggestions = await suggestPOVs(query)
        setPOVSuggestions(suggestions)
        // Show suggestions if input is focused and has suggestions
        if (povInputRef.current === document.activeElement) {
          setShowPOVSuggestions(suggestions.length > 0)
        }
      } catch (error) {
        console.error("Failed to get POV suggestions", error)
        setPOVSuggestions([])
        setShowPOVSuggestions(false)
      }
    }, 300)

    return () => clearTimeout(timer)
  }, [manualPOVInput])

  const createPostMutation = useMutation({
    mutationFn: (data: { text: string; povs: string[] }) =>
      createPost(data.text, data.povs),
    onSuccess: () => {
      setInputText("")
      setManualPOVs([])
      setAutoGeneratedPOVs([])
      setManualPOVInput("")
      queryClient.invalidateQueries({ queryKey: ["timeline"] })
      onPostCreated?.()
    },
  })

  const addManualPOV = () => {
    // Allow spaces in POV names, only trim leading/trailing spaces
    let trimmed = manualPOVInput.trim()
    if (trimmed.startsWith("#")) {
      trimmed = trimmed.slice(1).trim()
    }
    if (!trimmed || manualPOVs.includes(trimmed)) return
    // Validate POV length (max 300 characters)
    if (trimmed.length > 300) {
      alert("POV must be 300 characters or less")
      return
    }
    setManualPOVs((prev) => [...prev, trimmed])
    setManualPOVInput("")
  }

  const removeManualPOV = (pov: string) => {
    setManualPOVs((prev) => prev.filter((p) => p !== pov))
  }

  const handlePOVSuggestionClick = (pov: string) => {
    if (!manualPOVs.includes(pov)) {
      setManualPOVs((prev) => [...prev, pov])
    }
    setManualPOVInput("")
    setShowPOVSuggestions(false)
    povInputRef.current?.focus()
  }

  const handleAutoGeneratedPOVClick = (pov: string) => {
    if (!manualPOVs.includes(pov)) {
      setManualPOVs((prev) => [...prev, pov])
      // Remove from auto-generated list
      setAutoGeneratedPOVs((prev) => prev.filter((p) => p !== pov))
    }
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!inputText.trim()) return
    if (!user) {
      onAuthRequired()
      return
    }

    // Combine manual POVs (auto-generated POVs are already added to manualPOVs when clicked)
    const allPOVs = [...manualPOVs]
    createPostMutation.mutate({ text: inputText, povs: allPOVs })
  }

  return (
    <div className="bg-white rounded-xl sm:rounded-2xl shadow-md border border-slate-200/50 overflow-hidden">
      <div className="p-3 sm:p-4 border-b border-slate-100 bg-gradient-to-r from-blue-50/50 to-purple-50/50">
        <h2 className="text-xs sm:text-sm font-semibold text-slate-700 flex items-center gap-1.5 sm:gap-2">
          <span className="w-1.5 h-1.5 sm:w-2 sm:h-2 bg-blue-500 rounded-full"></span>
          What's on your mind?
        </h2>
      </div>
      <div className="p-3 sm:p-4">
        <form onSubmit={handleSubmit} className="space-y-4">
          <label htmlFor="post-content" className="sr-only">
            What's on your mind?
          </label>
          <div className="relative">
            <textarea
              id="post-content"
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              onKeyDown={(e) => {
                // Ctrl+Enter (or Cmd+Enter on Mac) to submit
                if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
                  e.preventDefault()
                  if (inputText.trim() && !createPostMutation.isPending) {
                    handleSubmit(e as any)
                  }
                }
              }}
              placeholder="Share your thoughts... (Ctrl+Enter to post)"
              className="w-full min-h-24 sm:min-h-32 p-3 sm:p-4 pr-12 sm:pr-14 bg-slate-50 rounded-lg sm:rounded-xl border-2 border-slate-200 focus:border-blue-400 focus:ring-2 focus:ring-blue-100 resize-none text-sm sm:text-base text-slate-800 placeholder:text-slate-400 leading-relaxed"
            />
            <button
              type="submit"
              disabled={createPostMutation.isPending || !inputText.trim()}
              className="absolute bottom-3 sm:bottom-4 right-3 sm:right-4 p-2 sm:p-2.5 bg-gradient-to-r from-blue-500 to-purple-500 text-white rounded-full hover:from-blue-600 hover:to-purple-600 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-md hover:shadow-lg"
            >
              {createPostMutation.isPending ? (
                <Loader2 size={16} className="sm:w-[18px] sm:h-[18px] animate-spin" />
              ) : (
                <Send size={16} className="sm:w-[18px] sm:h-[18px]" />
              )}
            </button>
          </div>

          {/* POV Suggestions display */}
          {(autoGeneratedPOVs.length > 0 || isGeneratingPOVs) && (
            <div className="pt-2 border-t border-slate-100">
              <div className="flex items-center gap-2 mb-2">
                <Sparkles size={14} className="text-purple-500" />
                <span className="text-xs font-medium text-slate-600">
                  POV Suggestions {isGeneratingPOVs && "(analyzing...)"}
                </span>
                {autoGeneratedPOVs.length > 0 && (
                  <span className="text-xs text-slate-400">(Click to use)</span>
                )}
              </div>
              {autoGeneratedPOVs.length > 0 ? (
                <div className="flex flex-wrap gap-2">
                  {autoGeneratedPOVs.map((pov) => (
                    <button
                      key={pov}
                      type="button"
                      onClick={() => handleAutoGeneratedPOVClick(pov)}
                      className="group px-3 py-1.5 bg-gradient-to-r from-purple-50 to-pink-50 text-purple-600 rounded-full text-sm font-medium hover:from-purple-100 hover:to-pink-100 transition-all border border-purple-200 flex items-center gap-1.5 shadow-sm hover:shadow-md active:scale-95"
                      title="Click to add this POV"
                    >
                      <Sparkles size={12} className="text-purple-500" />
                      <span>#{pov}</span>
                      <span className="text-xs opacity-0 group-hover:opacity-100 transition-opacity text-purple-500 font-semibold ml-1">
                        + Use
                      </span>
                    </button>
                  ))}
                </div>
              ) : isGeneratingPOVs ? (
                <div className="text-xs text-slate-400 italic">Analyzing your text...</div>
              ) : null}
            </div>
          )}

          {/* Selected POVs display */}
          {manualPOVs.length > 0 && (
            <div className="flex flex-wrap gap-2 pt-2 border-t border-slate-100">
              <span className="text-xs text-slate-500 self-center">Selected POVs:</span>
              {manualPOVs.map((pov) => {
                const isAutoGenerated = autoGeneratedPOVs.includes(pov)
                return (
                  <span
                    key={pov}
                    className={`px-2.5 py-1 rounded-full text-sm font-medium hover:opacity-80 transition-colors cursor-pointer flex items-center gap-1.5 ${isAutoGenerated
                        ? "bg-gradient-to-r from-purple-50 to-pink-50 text-purple-600 border border-purple-200"
                        : "bg-blue-50 text-blue-600"
                      }`}
                    onClick={() => removeManualPOV(pov)}
                  >
                    {isAutoGenerated && <Sparkles size={12} className="text-purple-500" />}
                    <span>#{pov}</span>
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation()
                        removeManualPOV(pov)
                      }}
                      className={`hover:opacity-70 rounded-full p-0.5 -mr-1 ${isAutoGenerated ? "hover:bg-purple-200" : "hover:bg-blue-200"
                        }`}
                    >
                      <X size={10} />
                    </button>
                  </span>
                )
              })}
            </div>
          )}

          {/* Manual POV input with suggestions */}
          <div className="pt-2 border-t border-slate-100 relative">
            <div className="flex gap-2 items-center">
              <span className="text-slate-400 text-sm">#</span>
              <div className="flex-1 relative">
                <input
                  ref={povInputRef}
                  type="text"
                  value={manualPOVInput}
                  maxLength={300}
                  onChange={(e) => {
                    let value = e.target.value
                    if (value.startsWith("#")) {
                      value = value.slice(1)
                    }
                    // Limit to 300 characters
                    if (value.length > 300) {
                      value = value.slice(0, 300)
                    }
                    setManualPOVInput(value)
                  }}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") {
                      e.preventDefault()
                      // If suggestions are shown and there's a first suggestion, use it
                      if (showPOVSuggestions && povSuggestions.length > 0 && !manualPOVInput.trim()) {
                        handlePOVSuggestionClick(povSuggestions[0])
                      } else {
                        addManualPOV()
                      }
                    } else if (e.key === "Escape") {
                      setShowPOVSuggestions(false)
                    } else if (e.key === "ArrowDown") {
                      e.preventDefault()
                      // Focus first suggestion if available
                      if (povSuggestions.length > 0) {
                        setShowPOVSuggestions(true)
                      }
                    }
                  }}
                  onFocus={async () => {
                    if (povSuggestions.length > 0) {
                      setShowPOVSuggestions(true)
                    } else {
                      try {
                        const suggestions = await suggestPOVs("")
                        setPOVSuggestions(suggestions)
                        setShowPOVSuggestions(suggestions.length > 0)
                      } catch (error) {
                        console.error("Failed to get POV suggestions", error)
                      }
                    }
                  }}
                  onBlur={() => {
                    // Delay hiding to allow clicking on suggestions
                    setTimeout(() => setShowPOVSuggestions(false), 200)
                  }}
                  placeholder="Add POV (Enter to add, max 300 chars)"
                  className="w-full px-2 py-1.5 bg-slate-50 rounded-lg border border-slate-200 focus:ring-2 focus:ring-blue-200 focus:border-blue-300 text-slate-700 placeholder:text-slate-400 text-sm"
                />
                {manualPOVInput.length > 250 && (
                  <div className="absolute top-full left-0 right-0 mt-1 text-xs text-slate-500 px-2">
                    {manualPOVInput.length}/300 characters
                  </div>
                )}
                {showPOVSuggestions && povSuggestions.length > 0 && (
                  <div className="absolute top-full left-0 right-0 mt-1 bg-white border border-slate-200 rounded-lg shadow-lg z-50 max-h-48 overflow-y-auto">
                    {manualPOVInput.trim() ? (
                      <div className="px-3 py-2 text-xs text-slate-500 border-b border-slate-100">
                        Suggestions for &quot;{manualPOVInput}&quot;
                      </div>
                    ) : (
                      <div className="px-3 py-2 text-xs text-slate-500 border-b border-slate-100">
                        Popular POVs
                      </div>
                    )}
                    {povSuggestions.map((pov) => (
                      <button
                        key={pov}
                        type="button"
                        onClick={() => handlePOVSuggestionClick(pov)}
                        onMouseDown={(e) => {
                          // Prevent input blur before click
                          e.preventDefault()
                        }}
                        className="w-full px-3 py-2 text-left text-sm text-slate-700 hover:bg-blue-50 transition-colors flex items-center gap-2"
                      >
                        <span className="text-blue-600">#</span>
                        <span className="flex-1">{pov}</span>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  )
}
