import { useMutation, useQueryClient } from "@tanstack/react-query"
import type React from "react"
import type { User } from "../api/client"
import { createPost } from "../api/client"
import { useI18n } from "../i18n"
import { AutoPOVSuggestions } from "./PostInputForm/AutoPOVSuggestions"
import { ManualPOVInput } from "./PostInputForm/ManualPOVInput"
import { SelectedPOVChips } from "./PostInputForm/SelectedPOVChips"
import { TextComposer } from "./PostInputForm/TextComposer"
import { usePostComposer } from "./PostInputForm/usePostComposer"

interface PostInputFormProps {
  user: User | null
  onAuthRequired: () => void
  onPostCreated?: () => void
}

export const PostInputForm: React.FC<PostInputFormProps> = ({
  user,
  onAuthRequired,
  onPostCreated,
}) => {
  const { t } = useI18n()
  const queryClient = useQueryClient()
  const composer = usePostComposer({
    onPovTooLong: () => alert(t("postForm.povTooLong")),
  })

  const createPostMutation = useMutation({
    mutationFn: (data: { text: string; povs: string[] }) =>
      createPost(data.text, data.povs),
    onSuccess: () => {
      composer.reset()
      queryClient.invalidateQueries({ queryKey: ["timeline"] })
      onPostCreated?.()
    },
  })

  const submitPost = () => {
    if (!composer.inputText.trim()) return
    if (!user) {
      onAuthRequired()
      return
    }
    createPostMutation.mutate({
      text: composer.inputText,
      povs: [...composer.manualPOVs],
    })
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    submitPost()
  }

  return (
    <div className="bg-[#1f1f35] rounded-lg border border-cyan-500/15 overflow-hidden">
      <div className="p-3 sm:p-4 border-b border-cyan-500/15 bg-[#2a2a50]">
        <h2 className="text-xs sm:text-sm font-semibold text-cyan-200 flex items-center gap-1.5 sm:gap-2 font-mono">
          <span className="w-1.5 h-1.5 sm:w-2 sm:h-2 bg-cyan-400/70 rounded-full" />
          {t("postForm.title")}
        </h2>
      </div>
      <div className="p-3 sm:p-4">
        <form onSubmit={handleSubmit} className="space-y-4">
          <TextComposer
            value={composer.inputText}
            isSubmitting={createPostMutation.isPending}
            onChange={composer.setInputText}
            onSubmitShortcut={submitPost}
          />

          <AutoPOVSuggestions
            povs={composer.autoGeneratedPOVs}
            isGenerating={composer.isGeneratingPOVs}
            onAdd={composer.addAutoGeneratedPOV}
          />

          <SelectedPOVChips
            povs={composer.manualPOVs}
            autoGeneratedPOVs={composer.autoGeneratedPOVs}
            onRemove={composer.removeManualPOV}
          />

          <ManualPOVInput
            inputRef={composer.povInputRef}
            value={composer.manualPOVInput}
            suggestions={composer.povSuggestions}
            showSuggestions={composer.showPOVSuggestions}
            onValueChange={composer.setManualPOVInputValue}
            onAdd={composer.addManualPOV}
            onSuggestionClick={composer.addSuggestedPOV}
            onShowSuggestionsChange={composer.setShowPOVSuggestions}
          />
        </form>
      </div>
    </div>
  )
}
