import { Loader2, Send, X, Sparkles } from "lucide-react"
import type React from "react"
import { useState, useEffect, useRef } from "react"
import { useMutation, useQueryClient } from "@tanstack/react-query"
import { createPost, suggestPOVs, generatePOVs } from "../api/client"
import type { User } from "../api/client"
import { POST_CONSTRAINTS } from "../types/constants"

interface PostInputFormProps {
  user: User | null
  onAuthRequired: () => void
  onPostCreated?: () => void
}

export const PostInputForm: React.FC<PostInputFormProps> = ({ user, onAuthRequired, onPostCreated }) => {
  const [inputText, setInputText] = useState<string>("")
  const [manualPOVInput, setManualPOVInput] = useState<string>("")
  const [manualPOVs, setManualPOVs] = useState<string[]>([])
  const [autoGeneratedPOVs, setAutoGeneratedPOVs] = useState<string[]>([])
  const [isGeneratingPOVs, setIsGeneratingPOVs] = useState(false)
  const [povSuggestions, setPOVSuggestions] = useState<string[]>([])
  const [showPOVSuggestions, setShowPOVSuggestions] = useState(false)
  const povInputRef = useRef<HTMLInputElement>(null)

  const queryClient = useQueryClient()

  // Auto-generate POVs from text content
  useEffect(() => {
    if (!inputText.trim()) {
      setAutoGeneratedPOVs([])
      setIsGeneratingPOVs(false)
      return
    }

    setIsGeneratingPOVs(true)
    const timer = setTimeout(async () => {
      try {
        const generatedPOVs = await generatePOVs(inputText)
        // Filter out POVs that are already manually added
        const filteredPOVs = generatedPOVs.filter(
          (pov) => !manualPOVs.includes(pov) && pov.length <= 300
        )
        setAutoGeneratedPOVs(filteredPOVs)
      } catch (error) {
        console.error("Failed to generate POVs from text", error)
        setAutoGeneratedPOVs([])
      } finally {
        setIsGeneratingPOVs(false)
      }
    }, 800) // Debounce for 800ms

    return () => {
      clearTimeout(timer)
      setIsGeneratingPOVs(false)
    }
  }, [inputText, manualPOVs])

  // POV suggestions for manual input
  useEffect(() => {
    // Always fetch suggestions when input changes (empty query returns popular POVs)
    const timer = setTimeout(async () => {
      try {
        const query = manualPOVInput.trim()
        const suggestions = await suggestPOVs(query)
        setPOVSuggestions(suggestions)
        // Show suggestions if input is focused and has suggestions
        if (povInputRef.current === document.activeElement) {
          setShowPOVSuggestions(suggestions.length > 0)
        }
      } catch (error) {
        console.error("Failed to get POV suggestions", error)
        setPOVSuggestions([])
        setShowPOVSuggestions(false)
      }
    }, 300)

    return () => clearTimeout(timer)
  }, [manualPOVInput])

  const createPostMutation = useMutation({
    mutationFn: (data: { text: string; povs: string[] }) =>
      createPost(data.text, data.povs),
    onSuccess: () => {
      setInputText("")
      setManualPOVs([])
      setAutoGeneratedPOVs([])
      setManualPOVInput("")
      queryClient.invalidateQueries({ queryKey: ["timeline"] })
      onPostCreated?.()
    },
  })

  const addManualPOV = () => {
    // Allow spaces in POV names, only trim leading/trailing spaces
    let trimmed = manualPOVInput.trim()
    if (trimmed.startsWith("#")) {
      trimmed = trimmed.slice(1).trim()
    }
    if (!trimmed || manualPOVs.includes(trimmed)) return
    // Validate POV length (max 300 characters)
    if (trimmed.length > 300) {
      alert("POV must be 300 characters or less")
      return
    }
    setManualPOVs((prev) => [...prev, trimmed])
    setManualPOVInput("")
  }

  const removeManualPOV = (pov: string) => {
    setManualPOVs((prev) => prev.filter((p) => p !== pov))
  }

  const handlePOVSuggestionClick = (pov: string) => {
    if (!manualPOVs.includes(pov)) {
      setManualPOVs((prev) => [...prev, pov])
    }
    setManualPOVInput("")
    setShowPOVSuggestions(false)
    povInputRef.current?.focus()
  }

  const handleAutoGeneratedPOVClick = (pov: string) => {
    if (!manualPOVs.includes(pov)) {
      setManualPOVs((prev) => [...prev, pov])
      // Remove from auto-generated list
      setAutoGeneratedPOVs((prev) => prev.filter((p) => p !== pov))
    }
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!inputText.trim()) return
    if (!user) {
      onAuthRequired()
      return
    }

    // Combine manual POVs (auto-generated POVs are already added to manualPOVs when clicked)
    const allPOVs = [...manualPOVs]
    createPostMutation.mutate({ text: inputText, povs: allPOVs })
  }

  return (
    <div className="bg-[#1f1f35] rounded-lg border border-cyan-500/15 overflow-hidden">
      <div className="p-3 sm:p-4 border-b border-cyan-500/15 bg-[#2a2a50]">
        <h2 className="text-xs sm:text-sm font-semibold text-cyan-200 flex items-center gap-1.5 sm:gap-2 font-mono">
          <span className="w-1.5 h-1.5 sm:w-2 sm:h-2 bg-cyan-400/70 rounded-full"></span>
          WHAT'S ON YOUR MIND?
        </h2>
      </div>
      <div className="p-3 sm:p-4">
        <form onSubmit={handleSubmit} className="space-y-4">
          <label htmlFor="post-content" className="sr-only">
            What's on your mind?
          </label>
          <div className="relative">
            <textarea
              id="post-content"
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              onKeyDown={(e) => {
                // Ctrl+Enter (or Cmd+Enter on Mac) to submit
                if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
                  e.preventDefault()
                  if (inputText.trim() && !createPostMutation.isPending) {
                    handleSubmit(e as any)
                  }
                }
              }}
              placeholder="SHARE YOUR THOUGHTS IN DEPTH... (CTRL+ENTER TO POST)"
              maxLength={POST_CONSTRAINTS.MAX_TEXT_LENGTH}
              className="w-full min-h-32 sm:min-h-48 p-3 sm:p-4 pr-12 sm:pr-14 bg-[#2a2a50] rounded-lg border border-cyan-500/15 focus:border-cyan-500/35 focus:ring-1 focus:ring-cyan-500/20 resize-y text-sm sm:text-base text-cyan-100 placeholder:text-cyan-300/70 leading-relaxed font-mono transition-all"
            />
            <button
              type="submit"
              disabled={createPostMutation.isPending || !inputText.trim()}
              className="absolute bottom-3 sm:bottom-4 right-3 sm:right-4 p-2 sm:p-2.5 bg-gradient-to-r from-cyan-500/90 to-fuchsia-500/90 text-black rounded-full hover:from-cyan-400 hover:to-fuchsia-400 disabled:opacity-50 disabled:cursor-not-allowed transition-all font-mono font-bold"
            >
              {createPostMutation.isPending ? (
                <Loader2 size={16} className="sm:w-[18px] sm:h-[18px] animate-spin" />
              ) : (
                <Send size={16} className="sm:w-[18px] sm:h-[18px]" />
              )}
            </button>
          </div>

          <div className="flex justify-end -mt-2">
            <span
              className={`text-[11px] font-mono ${
                inputText.length > POST_CONSTRAINTS.MAX_TEXT_LENGTH * 0.95
                  ? "text-fuchsia-400/90"
                  : "text-cyan-300/45"
              }`}
            >
              {inputText.length.toLocaleString()} / {POST_CONSTRAINTS.MAX_TEXT_LENGTH.toLocaleString()}
            </span>
          </div>

          {/* POV Suggestions display */}
          {(autoGeneratedPOVs.length > 0 || isGeneratingPOVs) && (
            <div className="pt-2 border-t border-cyan-500/12">
              <div className="flex items-center gap-2 mb-2">
                <Sparkles size={14} className="text-fuchsia-300/95" />
                <span className="text-xs font-medium text-fuchsia-300/95 font-mono">
                  POV SUGGESTIONS {isGeneratingPOVs && "(ANALYZING...)"}
                </span>
                {autoGeneratedPOVs.length > 0 && (
                  <span className="text-xs text-cyan-300/70 font-mono">(CLICK TO USE)</span>
                )}
              </div>
              {autoGeneratedPOVs.length > 0 ? (
                <div className="flex flex-wrap gap-2">
                  {autoGeneratedPOVs.map((pov) => (
                    <button
                      key={pov}
                      type="button"
                      onClick={() => handleAutoGeneratedPOVClick(pov)}
                      className="group px-2 py-1 bg-fuchsia-900/15 text-fuchsia-300/95 rounded text-xs font-mono hover:bg-fuchsia-900/25 transition-all border border-fuchsia-500/12 hover:border-fuchsia-500/40 flex items-center gap-1 active:scale-95"
                      title="Click to add this POV"
                    >
                      <Sparkles size={10} className="text-fuchsia-300/95" />
                      <span>#{pov}</span>
                      <span className="text-[10px] opacity-0 group-hover:opacity-100 transition-opacity text-fuchsia-300 font-semibold ml-1">
                        +
                      </span>
                    </button>
                  ))}
                </div>
              ) : isGeneratingPOVs ? (
                <div className="text-xs text-cyan-300/70 italic font-mono">ANALYZING YOUR TEXT...</div>
              ) : null}
            </div>
          )}

          {/* Selected POVs display */}
          {manualPOVs.length > 0 && (
            <div className="flex flex-wrap gap-2 pt-2 border-t border-cyan-500/12">
              <span className="text-xs text-cyan-300/80 self-center font-mono">SELECTED POVS:</span>
              {manualPOVs.map((pov) => {
                const isAutoGenerated = autoGeneratedPOVs.includes(pov)
                return (
                  <span
                    key={pov}
                    className={`px-2 py-0.5 rounded text-xs font-mono hover:opacity-80 transition-colors cursor-pointer flex items-center gap-1 border ${isAutoGenerated
                        ? "bg-fuchsia-900/15 text-fuchsia-300/95 border-fuchsia-500/12"
                        : "bg-cyan-900/15 text-cyan-300/95 border-cyan-500/12"
                      }`}
                    onClick={() => removeManualPOV(pov)}
                  >
                    {isAutoGenerated && <Sparkles size={10} className="text-fuchsia-300/95" />}
                    <span>#{pov}</span>
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation()
                        removeManualPOV(pov)
                      }}
                      className={`hover:opacity-70 rounded p-0.5 -mr-1 ${isAutoGenerated ? "hover:bg-fuchsia-900/30" : "hover:bg-cyan-900/30"
                        }`}
                    >
                      <X size={10} />
                    </button>
                  </span>
                )
              })}
            </div>
          )}

          {/* Manual POV input with suggestions */}
          <div className="pt-2 border-t border-cyan-500/12 relative">
            <div className="flex gap-2 items-center">
              <span className="text-cyan-300/80 text-sm font-mono">#</span>
              <div className="flex-1 relative">
                <input
                  ref={povInputRef}
                  type="text"
                  value={manualPOVInput}
                  maxLength={300}
                  onChange={(e) => {
                    let value = e.target.value
                    if (value.startsWith("#")) {
                      value = value.slice(1)
                    }
                    // Limit to 300 characters
                    if (value.length > 300) {
                      value = value.slice(0, 300)
                    }
                    setManualPOVInput(value)
                  }}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") {
                      e.preventDefault()
                      // If suggestions are shown and there's a first suggestion, use it
                      if (showPOVSuggestions && povSuggestions.length > 0 && !manualPOVInput.trim()) {
                        handlePOVSuggestionClick(povSuggestions[0])
                      } else {
                        addManualPOV()
                      }
                    } else if (e.key === "Escape") {
                      setShowPOVSuggestions(false)
                    } else if (e.key === "ArrowDown") {
                      e.preventDefault()
                      // Focus first suggestion if available
                      if (povSuggestions.length > 0) {
                        setShowPOVSuggestions(true)
                      }
                    }
                  }}
                  onFocus={async () => {
                    if (povSuggestions.length > 0) {
                      setShowPOVSuggestions(true)
                    } else {
                      try {
                        const suggestions = await suggestPOVs("")
                        setPOVSuggestions(suggestions)
                        setShowPOVSuggestions(suggestions.length > 0)
                      } catch (error) {
                        console.error("Failed to get POV suggestions", error)
                      }
                    }
                  }}
                  onBlur={() => {
                    setTimeout(() => setShowPOVSuggestions(false), 200)
                  }}
                  placeholder="ADD POV (ENTER TO ADD)"
                  className="w-full px-2 py-1.5 bg-[#1f1f3a] rounded border border-cyan-500/12 focus:ring-1 focus:ring-cyan-500/20 focus:border-cyan-500/18 text-cyan-200/95 placeholder:text-cyan-300/50 text-sm font-mono transition-all"
                />
                {manualPOVInput.length > 250 && (
                  <div className="absolute top-full left-0 right-0 mt-1 text-xs text-cyan-300/70 px-2 font-mono">
                    {manualPOVInput.length}/300 CHARACTERS
                  </div>
                )}
                {showPOVSuggestions && povSuggestions.length > 0 && (
                  <div className="absolute top-full left-0 right-0 mt-1 bg-[#151520] border border-cyan-500/12 rounded-lg z-50 max-h-48 overflow-y-auto">
                    {manualPOVInput.trim() ? (
                      <div className="px-3 py-2 text-xs text-cyan-300/80 border-b border-cyan-500/10 font-mono">
                        SUGGESTIONS FOR &quot;{manualPOVInput}&quot;
                      </div>
                    ) : (
                      <div className="px-3 py-2 text-xs text-cyan-300/80 border-b border-cyan-500/10 font-mono">
                        POPULAR POVS
                      </div>
                    )}
                    {povSuggestions.map((pov) => (
                      <button
                        key={pov}
                        type="button"
                        onClick={() => handlePOVSuggestionClick(pov)}
                        onMouseDown={(e) => {
                          // Prevent input blur before click
                          e.preventDefault()
                        }}
                        className="w-full px-3 py-2 text-left text-sm text-cyan-200/95 hover:bg-cyan-900/15 transition-colors flex items-center gap-2 font-mono border-b border-cyan-500/8 last:border-b-0"
                      >
                        <span className="text-fuchsia-300/90">#</span>
                        <span className="flex-1">{pov}</span>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  )
}
