import { Sparkles, X } from "lucide-react"
import type React from "react"
import { useI18n } from "../../i18n"

interface SelectedPOVChipsProps {
  povs: string[]
  autoGeneratedPOVs: string[]
  onRemove: (pov: string) => void
}

export const SelectedPOVChips: React.FC<SelectedPOVChipsProps> = ({
  povs,
  autoGeneratedPOVs,
  onRemove,
}) => {
  const { t } = useI18n()

  if (povs.length === 0) return null

  return (
    <div className="flex flex-wrap gap-2 pt-2 border-t border-cyan-500/12">
      <span className="text-xs text-cyan-300/80 self-center font-mono">
        {t("postForm.selectedPovs")}
      </span>
      {povs.map((pov) => {
        const isAutoGenerated = autoGeneratedPOVs.includes(pov)
        return (
          <span
            key={pov}
            className={`px-2 py-0.5 rounded text-xs font-mono hover:opacity-80 transition-colors flex items-center gap-1 border ${
              isAutoGenerated
                ? "bg-fuchsia-900/15 text-fuchsia-300/95 border-fuchsia-500/12"
                : "bg-cyan-900/15 text-cyan-300/95 border-cyan-500/12"
            }`}
          >
            {isAutoGenerated && (
              <Sparkles size={10} className="text-fuchsia-300/95" />
            )}
            <span>#{pov}</span>
            <button
              type="button"
              onClick={(e) => {
                e.stopPropagation()
                onRemove(pov)
              }}
              className={`hover:opacity-70 rounded p-0.5 -mr-1 ${
                isAutoGenerated
                  ? "hover:bg-fuchsia-900/30"
                  : "hover:bg-cyan-900/30"
              }`}
              aria-label={t("search.removeTag", { tag: pov })}
              title={t("search.removeTag", { tag: pov })}
            >
              <X size={10} />
            </button>
          </span>
        )
      })}
    </div>
  )
}
