import { useEffect, useRef, useState } from "react"
import { generatePOVs, suggestPOVs } from "../../api/client"
import { DEBOUNCE_DELAYS, POV_CONSTRAINTS } from "../../types/constants"

interface UsePostComposerOptions {
  onPovTooLong: () => void
}

export function usePostComposer({ onPovTooLong }: UsePostComposerOptions) {
  const [inputText, setInputText] = useState("")
  const [manualPOVInput, setManualPOVInput] = useState("")
  const [manualPOVs, setManualPOVs] = useState<string[]>([])
  const [autoGeneratedPOVs, setAutoGeneratedPOVs] = useState<string[]>([])
  const [isGeneratingPOVs, setIsGeneratingPOVs] = useState(false)
  const [povSuggestions, setPOVSuggestions] = useState<string[]>([])
  const [showPOVSuggestions, setShowPOVSuggestions] = useState(false)
  const povInputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    if (!inputText.trim()) {
      setAutoGeneratedPOVs([])
      setIsGeneratingPOVs(false)
      return
    }

    setIsGeneratingPOVs(true)
    const timer = setTimeout(async () => {
      try {
        const generatedPOVs = await generatePOVs(inputText)
        setAutoGeneratedPOVs(
          generatedPOVs.filter(
            (pov) =>
              !manualPOVs.includes(pov) &&
              pov.length <= POV_CONSTRAINTS.MAX_LENGTH,
          ),
        )
      } catch (error) {
        console.error("Failed to generate POVs from text", error)
        setAutoGeneratedPOVs([])
      } finally {
        setIsGeneratingPOVs(false)
      }
    }, DEBOUNCE_DELAYS.POV_GENERATION)

    return () => {
      clearTimeout(timer)
      setIsGeneratingPOVs(false)
    }
  }, [inputText, manualPOVs])

  useEffect(() => {
    const timer = setTimeout(async () => {
      try {
        const suggestions = await suggestPOVs(manualPOVInput.trim())
        setPOVSuggestions(suggestions)
        if (povInputRef.current === document.activeElement) {
          setShowPOVSuggestions(suggestions.length > 0)
        }
      } catch (error) {
        console.error("Failed to get POV suggestions", error)
        setPOVSuggestions([])
        setShowPOVSuggestions(false)
      }
    }, DEBOUNCE_DELAYS.POV_SUGGESTION)

    return () => clearTimeout(timer)
  }, [manualPOVInput])

  const setManualPOVInputValue = (value: string) => {
    const normalized = value.startsWith("#") ? value.slice(1) : value
    setManualPOVInput(normalized.slice(0, POV_CONSTRAINTS.MAX_LENGTH))
  }

  const addManualPOV = () => {
    let trimmed = manualPOVInput.trim()
    if (trimmed.startsWith("#")) {
      trimmed = trimmed.slice(1).trim()
    }
    if (!trimmed || manualPOVs.includes(trimmed)) return
    if (trimmed.length > POV_CONSTRAINTS.MAX_LENGTH) {
      onPovTooLong()
      return
    }
    setManualPOVs((prev) => [...prev, trimmed])
    setManualPOVInput("")
  }

  const removeManualPOV = (pov: string) => {
    setManualPOVs((prev) => prev.filter((p) => p !== pov))
  }

  const addSuggestedPOV = (pov: string) => {
    if (!manualPOVs.includes(pov)) {
      setManualPOVs((prev) => [...prev, pov])
    }
    setManualPOVInput("")
    setShowPOVSuggestions(false)
    povInputRef.current?.focus()
  }

  const addAutoGeneratedPOV = (pov: string) => {
    if (!manualPOVs.includes(pov)) {
      setManualPOVs((prev) => [...prev, pov])
      setAutoGeneratedPOVs((prev) => prev.filter((p) => p !== pov))
    }
  }

  const reset = () => {
    setInputText("")
    setManualPOVs([])
    setAutoGeneratedPOVs([])
    setManualPOVInput("")
    setShowPOVSuggestions(false)
  }

  return {
    inputText,
    setInputText,
    manualPOVInput,
    setManualPOVInputValue,
    manualPOVs,
    autoGeneratedPOVs,
    isGeneratingPOVs,
    povSuggestions,
    showPOVSuggestions,
    setShowPOVSuggestions,
    povInputRef,
    addManualPOV,
    removeManualPOV,
    addSuggestedPOV,
    addAutoGeneratedPOV,
    reset,
  }
}
